### ISSUE TITLE
Produce a list of names that need refunding due to normalisation change

### ISSUE THREAD

**Issue by makoto** [ensdomains/pm#37]
## Summary

Once the new ens_normalize normalisation logic replaces the old logic of eth-ens-namehash, there are two types of users those names won't be usable

- a. old normalization worked but new normalization throws an error
- b. both old and new normalisation work but normalise into different values (hence different namehash and tokenid)

Here is the example dataset from https://console.cloud.google.com/bigquery?sq=329024247671:e2bd661ca2514c23b75a1dc7aeb1ab56

<img width="1150" alt="Screenshot 2022-09-08 at 11 48 16" src="https://user-images.githubusercontent.com/2630/189103787-fad5c1ee-9f98-45e3-8a2d-200d0f3907c0.png">

The task is to identify these users for a potential refund

## Tasks

- [x] Exclude `label != namehash(label)` (It wasn't resolvable and our site shows as malmormatted from the beginning so no need for refunding)
- [x] List names that qualify for a.
- [x] List names that qualify for b. 
- [x] Use the latest version of ens_normalize ([the current version has an issue porting into BigQuery UDF](https://github.com/adraffy/ens-normalize.js/issues/4)) 
- [x] [Create a script to convert npm module into portable javascript UDF ](https://github.com/ensdomains/ens-bigquery-udf)
- [ ] Check if the data is accurate

## Reference
- https://adraffy.github.io/ens-norm-tests/test-compare/output/ens_normalize_1.5.0_vs_eth-ens-namehash_2.0.15.html#b-error
- https://discuss.ens.domains/t/ens-name-normalization/8652/394

## Output

- https://console.cloud.google.com/bigquery?sq=329024247671:25d304fb9c13406b96bf08aaa1fb43cb

**Comment by makoto** [comment]
All the names (big query)
- https://console.cloud.google.com/bigquery?sq=329024247671:25d304fb9c13406b96bf08aaa1fb43cb

Refund addresses (csv)
- https://drive.google.com/drive/folders/1tHyERa0uU4GdaVnOMgD0Iw6LqkwJ6M3s

Summary

<img width="1119" alt="Screenshot 2022-09-19 at 11 05 06" src="https://user-images.githubusercontent.com/2630/190995095-a9357a6d-afab-4af3-9acb-8e9601a196d4.png">

**Comment by makoto** [comment]
I updated the `ens-normalize.js` to the latest (1.9.0) and rerun the query.

The total refund address increased from 4905 to 11,226.
The total refund amount increased from 168.44 ETH to 281.62 ETH

The full refund address is https://docs.google.com/spreadsheets/d/1Ixt630-vw-CEcjlbvUcqKa7w5YU4e8Iu72EN23V2QHY/edit#gid=1055247876

The breakdown of the errored name and the different names is
https://colab.research.google.com/drive/1efD0YkknERbojmIxdoTwhofsrDG5UEnG#scrollTo=CvPNVSRBg04x
